// <auto-generated />
using CitiesConsumingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CitiesConsumingAPI.Migrations
{
    [DbContext(typeof(CitiesDbContext))]
    [Migration("20221218185348_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CitiesLibrary.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("CityId")
                        .HasName("pk_cities");

                    b.ToTable("cities", (string)null);

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            Name = "Tokyo"
                        },
                        new
                        {
                            CityId = 2,
                            Name = "Tokyo"
                        },
                        new
                        {
                            CityId = 3,
                            Name = "Tokyo"
                        },
                        new
                        {
                            CityId = 4,
                            Name = "Tokyo"
                        },
                        new
                        {
                            CityId = 5,
                            Name = "Tokyo"
                        },
                        new
                        {
                            CityId = 6,
                            Name = "Tokyo"
                        },
                        new
                        {
                            CityId = 7,
                            Name = "Tokyo"
                        },
                        new
                        {
                            CityId = 8,
                            Name = "Tokyo"
                        },
                        new
                        {
                            CityId = 9,
                            Name = "Tokyo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
